# -- mode: ruby --
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   	
   config.vm.define :servidorpxe do |servidorpxe|
	servidorpxe.vm.box = "bento/centos-7.9"
	servidorpxe.vm.network :private_network, ip: "172.168.1.11"
	servidorpxe.vm.hostname = "servidorpxe"
	
end
end